stages:
- deploy

deploy_production:
  stage: deploy
  image: python:3.8-buster

  before_script:
    - pip install twine

  script:
    - python setup.py sdist
    - twine upload dist/*

  rules:
    - if: $CI_COMMIT_TAG
