# Generated by Django 3.1.1 on 2020-09-30 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Can access this app'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='DestinationAADiscordBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('CM', 'Channel Message'), ('DM', 'Direct Message')], default='CM', max_length=2)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.channels')),
            ],
        ),
        migrations.CreateModel(
            name='DestinationWebhooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('server', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('Discord', 'Discord'), ('Slack', 'Slack'), ('XMPP', 'XMPP')], default='Discord', max_length=10)),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
            },
        ),
        migrations.CreateModel(
            name='RelayConfigurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_aadiscordbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.destinationaadiscordbot')),
                ('destination_webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.destinationwebhooks')),
                ('source_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.channels')),
                ('source_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.servers')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('message', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.channels')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.AddField(
            model_name='channels',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aarelays.servers'),
        ),
        migrations.CreateModel(
            name='AccessTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servers', models.ManyToManyField(to='aarelays.Servers')),
            ],
            options={
                'verbose_name': 'Access Token',
                'verbose_name_plural': 'Access Tokens',
            },
        ),
    ]
