# Generated by Django 3.1.2 on 2020-10-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarelays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='author',
            field=models.CharField(default='Ariel_Rin', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='destination_db',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='message_mention',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='message_non_mention',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='message_regex',
            field=models.CharField(default='.^', max_length=10),
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='source_channel_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='source_server_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesstokens',
            name='servers',
            field=models.ManyToManyField(blank=True, to='aarelays.Servers'),
        ),
    ]
