# Generated by Django 3.1.1 on 2020-10-01 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aarelays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
