# Generated by Django 3.1.2 on 2020-10-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarelays', '0006_auto_20201021_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayconfigurations',
            name='destination_aadiscordbot',
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='destination_aadiscordbot',
            field=models.ManyToManyField(blank=True, to='aarelays.DestinationAADiscordBot'),
        ),
        migrations.RemoveField(
            model_name='relayconfigurations',
            name='destination_webhook',
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='destination_webhook',
            field=models.ManyToManyField(blank=True, to='aarelays.DestinationWebhooks'),
        ),
        migrations.RemoveField(
            model_name='relayconfigurations',
            name='source_channel',
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='source_channel',
            field=models.ManyToManyField(to='aarelays.Channels'),
        ),
        migrations.RemoveField(
            model_name='relayconfigurations',
            name='source_server',
        ),
        migrations.AddField(
            model_name='relayconfigurations',
            name='source_server',
            field=models.ManyToManyField(to='aarelays.Servers'),
        ),
    ]
