# Generated by Django 3.1.2 on 2020-10-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarelays', '0007_auto_20201022_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='author_nick',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='author',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='relayconfigurations',
            name='destination_aadiscordbot',
            field=models.ManyToManyField(blank=True, null=True, to='aarelays.DestinationAADiscordBot'),
        ),
        migrations.AlterField(
            model_name='relayconfigurations',
            name='destination_webhook',
            field=models.ManyToManyField(blank=True, null=True, to='aarelays.DestinationWebhooks'),
        ),
    ]
