# Generated by Django 3.1.2 on 2020-10-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aarelays', '0008_auto_20201022_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayconfigurations',
            name='destination_aadiscordbot',
            field=models.ManyToManyField(blank=True, to='aarelays.DestinationAADiscordBot'),
        ),
        migrations.AlterField(
            model_name='relayconfigurations',
            name='destination_webhook',
            field=models.ManyToManyField(blank=True, to='aarelays.DestinationWebhooks'),
        ),
    ]
